name: CharacterKit
version: '1.0-SNAPSHOT'
main: Chisu.characterKit.CharacterKit
api-version: '1.21'

commands:
  BlueKit:
    description: Comando para obtener el CharacterKit de Blue
    aliases:
      - Blue
